config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost:3000'

  root to: 'urls#new'
  get '/m/:checksum', to: 'urls#show', as: :mini
  get '/stats', to: 'urls#index', as: :stats
  resources :urls, only: [:new, :create]
end

app/models/url.rb
class Url < ActiveRecord::Base
  validate :presence, :original

  before_create :sanitize_original
  before_create :generate_minified
  after_commit :set_expire_at

  has_many :visits

  def self.expire_month_old_urls
    expired_urls = Url.where('expired = ? AND expire_at < ?', false, DateTime.now)
    expired_urls.update_all(expired: true)
  end

  private
  def sanitize_original
    return false if self.original.blank?
    original.strip!
    sanitize_url = self.original.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
    self.original = "http://#{sanitize_url}"
  end

  def generate_minified
    self.checksum = rand(36**5).to_s(36)
  end

  def set_expire_at
    update_column(:expire_at, 1.month.from_now)
  end
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :url, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @visits = Url.includes(:visits)
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.new(url_params)
    @url.save
  end

  def show
    url = Url.find_by(checksum: params[:checksum], expired: false) 
    if url.nil?
      render 'public/404'
    else
      visit = url.visits.build(ip: request.remote_ip, country: request.location.try(:country))
      visit.save
      redirect_to url.original
    end
  end

  private

  def url_params
    params.require(:url).permit(:original)
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/urls/_minified_url.html.haml
- if @url.checksum?
  %p Here is your minified url
  = mini_url(checksum: @url.checksum)
- else
  %p Minified Url can not be generated

app/views/urls/create.js.haml
$('#minified_url').html("#{j(render partial: 'minified_url')}");

app/views/urls/index.html.haml
%h1 Analatyics
.row
  - @visits.each do |visited_url|
    %h3= visited_url.original
    %h5= mini_url(checksum: visited_url.checksum)
    %p Total Clicks : #{visited_url.visits_count}
    %p ip : #{visited_url.visits.map(&:ip).join(', ')}
    %hr

app/views/urls/new.html.haml
.row
  = form_for(@url, remote: true) do |f|
    = f.text_field :original
    = f.submit 'Minify', class: 'button-md'

.row
  #minified_url.bold